// Generated by `wit-bindgen` 0.52.0. DO NOT EDIT!
#ifndef __BINDINGS_HOST_H
#define __BINDINGS_HOST_H
#ifdef __cplusplus
extern "C" {
#endif

#include <stdint.h>
#include <stdbool.h>
#include <stddef.h>

// Exported Functions from `host`
void exports_host_run(void);

#ifdef __cplusplus
}
#endif
#endif
